
title: Miguel Garcia-Duch
page-top-title: Miguel Garcia-Duch
top-section-bg-text: Research and Data Engineering
home-subtitle: About me&ensp;
copyright-text: '&copy; Miguel Garcia-Duch 2025. All Rights Reserved.'
